# Generated by Django 4.2.3 on 2023-07-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='ourMission',
            field=models.CharField(default='Our Mission', max_length=500),
        ),
        migrations.AddField(
            model_name='about',
            name='ourVision',
            field=models.CharField(default='Our Vision', max_length=500),
        ),
    ]
